if(EXISTS "/usr/src/projects/aaa-p2/build_coverage/config_port_number_test[1]_tests.cmake")
  include("/usr/src/projects/aaa-p2/build_coverage/config_port_number_test[1]_tests.cmake")
else()
  add_test(config_port_number_test_NOT_BUILT config_port_number_test_NOT_BUILT)
endif()
