add_test( RequestParserTest.SimpleRequest /usr/src/projects/aaa-p2/build_coverage/bin/request_parser_test [==[--gtest_filter=RequestParserTest.SimpleRequest]==] --gtest_also_run_disabled_tests)
set_tests_properties( RequestParserTest.SimpleRequest PROPERTIES WORKING_DIRECTORY /usr/src/projects/aaa-p2/tests)
add_test( RequestParserTest.LongerRequest /usr/src/projects/aaa-p2/build_coverage/bin/request_parser_test [==[--gtest_filter=RequestParserTest.LongerRequest]==] --gtest_also_run_disabled_tests)
set_tests_properties( RequestParserTest.LongerRequest PROPERTIES WORKING_DIRECTORY /usr/src/projects/aaa-p2/tests)
add_test( RequestParserTest.MissingGET /usr/src/projects/aaa-p2/build_coverage/bin/request_parser_test [==[--gtest_filter=RequestParserTest.MissingGET]==] --gtest_also_run_disabled_tests)
set_tests_properties( RequestParserTest.MissingGET PROPERTIES WORKING_DIRECTORY /usr/src/projects/aaa-p2/tests)
add_test( RequestParserTest.ColonAfterGET /usr/src/projects/aaa-p2/build_coverage/bin/request_parser_test [==[--gtest_filter=RequestParserTest.ColonAfterGET]==] --gtest_also_run_disabled_tests)
set_tests_properties( RequestParserTest.ColonAfterGET PROPERTIES WORKING_DIRECTORY /usr/src/projects/aaa-p2/tests)
set( request_parser_test_TESTS RequestParserTest.SimpleRequest RequestParserTest.LongerRequest RequestParserTest.MissingGET RequestParserTest.ColonAfterGET)
