if(EXISTS "/usr/src/projects/aaa-p2/build_coverage/session_test[1]_tests.cmake")
  include("/usr/src/projects/aaa-p2/build_coverage/session_test[1]_tests.cmake")
else()
  add_test(session_test_NOT_BUILT session_test_NOT_BUILT)
endif()
